version: "3.5"

services:
  iam-service:
    build: ./iam
    image: iam-service
    container_name: iam-service
    restart: unless-stopped
    networks:
      - diplomski

  ticket-seller-service:
    build: ./ticket-seller
    image: ticket-seller-service
    container_name: ticket-seller-service
    restart: unless-stopped
    ports:
      - 5007:5007 # debug port
    networks:
      - diplomski

  post-service:
    build: ./postservice
    image: post-service
    container_name: post-service
    restart: unless-stopped
    volumes:
      - ./postservice/storage:/usr/src/demo/storage
    # ports:
      # - 5006:5006 # debug port
    networks:
      - diplomski

  notification-service:
    build: ./notificationsservice
    image: notification-service
    container_name: notification-service
    restart: unless-stopped
    networks: 
      - diplomski

  event-details-service:
    build: ./event_details_service
    image: event-details-service
    container_name: event-details-service
    restart: unless-stopped
    ports:
      - 5008:5008 # debug port
    networks: 
      - diplomski

  orchestration-service:
    build: ./orchestration-service
    image: orchestration-service
    container_name: orchestration-service
    restart: unless-stopped
    ports:
      - 8080:8080
      - 5005:5005 # debug port
    networks:
      - diplomski

networks:
  diplomski:
    external: true
