version: "3.5"

services:
  # nats-service:
  #   image: nats:latest
  #   container_name: nats-service
  #   expose:
  #     - "4222"
  #   networks:
  #     - diplomski

  # postgres-service:
  #   image: postgres
  #   container_name: postgres-service
  #   environment:
  #     POSTGRES_PASSWORD: root
  #     PGDATA: /usr/local/var/postgres
  #   volumes:
  #     - ./db-data:/usr/local/var/postgres
  #   expose:
  #     - "5432"

  iam-service:
    build: ./iam
    image: iam-service
    container_name: iam-service
    restart: unless-stopped
    networks:
      - diplomski

  ticket-seller-service:
    build: ./ticket-seller
    image: ticket-seller-service
    container_name: ticket-seller-service
    restart: unless-stopped
    networks:
      - diplomski

  orchestration-service:
    build: ./orchestration-service
    image: orchestration-seller-service
    container_name: orchestration-seller-service
    restart: unless-stopped
    ports: 
      - 8080:8080
    networks:
      - diplomski

networks:
  diplomski:
    external: true
