version: "3.5"

services:
  iam-service:
    build: ./iam
    image: iam-service
    container_name: iam-service
    restart: unless-stopped
    networks:
      - diplomski

  ticket-seller-service:
    build: ./ticket-seller
    image: ticket-seller-service
    container_name: ticket-seller-service
    restart: unless-stopped
    networks:
      - diplomski

  post-service:
    build: ./postservice
    image: post-service
    container_name: post-service
    restart: unless-stopped
    networks:
      - diplomski

  orchestration-service:
    build: ./orchestration-service
    image: orchestration-service
    container_name: orchestration-service
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - diplomski

networks:
  diplomski:
    external: true
