app:
  datasource:
    jdbc-url: jdbc:postgresql://postgres-service:5432/ticket-seller
    username: "postgres"
    password: "root"
    pool-size: 30

nats:
  host: nats://nats-service:4222
  # host: nats://localhost:4222

server:
  port: 8081